# Generated by Django 4.0.4 on 2022-05-16 22:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estadia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.CharField(default='', max_length=1000)),
                ('hora', models.CharField(default='', max_length=1000)),
                ('precio', models.CharField(default='', max_length=1000)),
                ('placa', models.CharField(default='', max_length=1000)),
                ('estado', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(default='', max_length=1000)),
                ('tipo', models.CharField(default='', max_length=1000)),
                ('documento_usuario', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documento', models.CharField(default='', max_length=1000)),
                ('nombres', models.CharField(default='', max_length=1000)),
                ('correo', models.CharField(default='', max_length=100)),
                ('telefono', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documento', models.CharField(default='', max_length=1000)),
                ('placa', models.CharField(default='', max_length=1000)),
                ('modelo', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
