# Generated by Django 4.0.4 on 2022-05-17 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Control_Parking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='documento',
            new_name='documento_usuario',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='documento',
            new_name='documento_usuario',
        ),
    ]
