# Generated by Django 4.0.4 on 2022-05-18 14:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('App_Control_Parking', '0002_rename_documento_usuario_documento_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LugarParqueo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_lugar', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Estadia',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_entrada',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='typology',
            field=models.ManyToManyField(blank=True, related_name='usuario', to='App_Control_Parking.usuario'),
        ),
    ]
