# Generated by Django 4.0.4 on 2022-06-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Control_Parking', '0005_remove_vehiculo_fecha_entrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugarparqueo',
            name='fecha_salida',
        ),
        migrations.RemoveField(
            model_name='lugarparqueo',
            name='precio_minuto',
        ),
        migrations.AddField(
            model_name='lugarparqueo',
            name='ocupado',
            field=models.BooleanField(default=False),
        ),
    ]
